name: CI

on:
  push:
    paths:
      - 'source/**.ts'
      - '*.json'
      - '.npmrc'
      - '.github/workflows/ci.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint ./source/

      - name: Compile TypeScript
        run: npx tsc

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }}
          path: |
            ./dist/
            ./package.json
            ./package-lock.json
